
import AuthComponent from "@/components/AuthComponent";
import "./globals.css";
import { createClient } from "@supabase/supabase-js";
import SupabaseProvider from "./supabase-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body>
        <AuthComponent />
        {children}
      </body>
    </html>
  );
}